config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users

  resources :users do
    resources :robots, only: [:edit, :update]
  end

  resources :equities do
    resources :contracts, only: [:create, :new]
  end

  namespace :api do
    resources :graphs, only: [:create] do
      collection do
        get 'graph_data'
      end
    end
  end

#Need to add more "excepts" to sessions

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  post "login" => "sessions#create"

  root 'sessions#new'
end

app/models/contract.rb
class Contract < ApplicationRecord
  include ContractsHelper

  belongs_to :user
  belongs_to :equity

  def expiration
    created_at.time + interval.minutes
  end

end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  include ContractsHelper

  def index
    if logged_in?
      @user = current_user
      @contracts = current_user.contracts
    else
      redirect_to new_user_path
    end
  end

  def new
    @contract = Contract.new
  end


  def create
    @contract = Contract.new(contract_params)
    if @contract.save
      purchase_time = alpha_time_adjustment(@contract.created_at)
      if markets_open?
        spot_price = Equity.get_price(@contract.ticker, purchase_time)
      else
        spot_price = Equity.get_price(@contract.ticker)
      end
      @equity = Equity.find(params[:equity_id])
      @contract.update_attributes(:spot_price => spot_price)
      if markets_open?
        CalculateGainLossJob.set(wait_until: @contract.expiration).perform_later @contract, current_user
      else
        gain_loss = 0
        @contract.update_attributes(:gain_loss => gain_loss)
      end
      redirect_to equity_path(@equity)
    else
      flash[:notice] = "Form is invalid"
      render 'show'
    end
  end

  def show
    @contract.Contract.new

  end

  private

  def contract_params
    params.require(:contract).permit(:ticker, :strike_price, :spot_price, :interval, :gain_loss, :expiration_date, :status, :put_call, :user_id, :equity_id)
  end
end

app/helpers/contracts_helper.rb
module ContractsHelper	
  def alpha_time_adjustment(purchase_time)
    adjusted_time = purchase_time - 4.hours
    adjusted_time.change(:sec => 0).strftime("%Y-%m-%d %H:%M:%S")
  end

  def markets_open?
    today_date = Time.now.strftime("%Y-%m-%d")
    if Time.now.strftime("%Y-%m-%d %H:%M:%S") < today_date + " 06:29:00" || 
       Time.now.strftime("%Y-%m-%d %H:%M:%S") > today_date + " 13:00:00" || 
       Date.today.saturday? || Date.today.sunday?
      return false
    end
    true
  end

end

app/views/contracts/index.html.erb
<!-- <h1>Contracts Index Page</h1>

<p>
  <%= link_to 'User Show Page', user_path(current_user) %>
</p>

<h3><%= @current_time %></h3>


<h4><%= link_to 'Trade Forex Markets', assets_path %></h4>

<% @contracts.each do |contract| %>
  <tr>
    <td><%= link_to contract.ticker, contract_path(contract) %></td>
  </tr><br>
  <tr>
    <% if contract.strike_price %>
      <td>Strike Price: $<%= contract.strike_price %></td><br>
      <td>Created at: <%= contract.created_at.in_time_zone("Pacific Time (US & Canada)") %></td><br>
      <td>Expiration: <%= contract.expiration.in_time_zone("Pacific Time (US & Canada)") %></td><br>
      <td>Spot Price: $<%= contract.spot_price %></td><br>
    <% end %>
    <% if contract.gain_loss == nil %>
      <% CalculateGainLossJob.set(wait_until: contract.expiration).perform_later contract %>
        <td><%= contract.gain_loss %></td><br>
    <% else %>
      <td><%= contract.gain_loss %></td><br>
    <% end %>
  </tr><br>

<% end %>

<div  class='main-image' ><%= render 'graphs/graph' %></div>

<div class='console'>

  <div class='stockbox'>
    <div class='button'><%= link_to "TSLA", contracts_path(:ticker => 'tsla')%></div>
    <div class='button'><%= link_to "GOOGL", contracts_path(:ticker => 'googl') %></div>
    <div class='button'><%= link_to "AAPL", contracts_path(:ticker => 'aapl') %></div>
    <div class='button'><%= link_to "FB", contracts_path(:ticker => 'fb') %></div>
    <div class='button'><%= link_to "TWTR", contracts_path(:symbol => 'twtr') %></div>
  </div>
</div>

<div class='infobox'>
   <ul class="tabs">
      <li><a href='#overview'>Overview</a></li>
      <li><a href='#fundamentals'>Fundamentals</a></li>
      <li><a href='#trade'>Trade</a></li>
  </ul>
  <div class='items'>
    <div id="overview" class='tab'>
      <%= render partial: "overview" %>
    </div>
    <div id="fundamentals" class='tab'>
      <%= render partial: "fundamentals" %>
    </div>
    <div id="trade" class='tab'>
      <%= render partial: "trade" %>
    </div>
  </div>
</div> -->

app/views/contracts/new.html.erb
<h1>New Contract Page</h1>

<%= form_for @contract do |f| %>
  <p>
    <%= f.label :ticker %>
    <%= f.text_field :ticker %>
  </p>
  <p>
    <%= f.label :strike_price %>
    <%= f.number_field :strike_price, class: :text_field, step: :any %>
  </p>
  <p>
    <%= f.label :interval %>
    <%= f.text_field :interval %>
  </p>
    <%= f.hidden_field :user_id, value: current_user.id %>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/contracts/show.html.erb
<h1>Contracts Show Page</h1>

<h3><%= @current_time %></h3>

<tr>
  <td><%= @contract.ticker %></td>
</tr><br>
<tr>
  <% if @contract.strike_price %>
    <td>Strike Price: $<%= @contract.strike_price %></td><br>
    <td>Created at: <%= @contract.created_at.in_time_zone("Pacific Time (US & Canada)") %></td><br>
    <td>Expiration: <%= @contract.expiration.in_time_zone("Pacific Time (US & Canada)") %></td><br>
    <td>Spot Price: $<%= @contract.spot_price %></td><br>
  <% end %>
</tr><br>

<p>
	<%= link_to 'Return to Contracts Index', contracts_path %>
</p>