config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users

  resources :users do
    resources :robots, only: [:edit, :update]
  end

  resources :equities do
    resources :contracts, only: [:create, :new]
  end

  namespace :api do
    resources :graphs, only: [:create] do
      collection do
        get 'graph_data'
      end
    end
  end

#Need to add more "excepts" to sessions

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  post "login" => "sessions#create"

  root 'sessions#new'
end

app/models/robot.rb
class Robot < ApplicationRecord
  belongs_to :user
  before_save :assign_url

  validates_presence_of :name

  def assign_url
    self.summon = "https://robohash.org/#{self.name}.png"
  end

end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController

  def edit
    @user = User.find(params[:id])
    @robot = @user.robot
  end

  def update
    p "*" * 100
    p
    @robot = Robot.find_by(user_id: params[:user_id])
    if @robot.update(name: params[:name])
      redirect_to equities_path
    else
      render 'edit'
    end
  end

end

app/views/robots/edit.html.erb
<div id="edit-robot-container">
  <div id="greeting">
      <h2>Welcome to PCP 🖖🏻 <br>
          My name is Frank. That-It. <br>
          Your mentor robot is <br>
          being created as we speak.
        </h2>
  </div>
  <div id="name-form">
    <h4>Please give your mentor robot a name:</h4> <br>

    <%= form_tag(user_robot_path ,method: "patch", remote: true, html: {id: 'change-robot-name'}) do %>
      <% if @robot.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @user.errors.full_messages %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <p class="fancy-field">
        <%= label_tag(:name, 'ROBOT NAME') %>
        <%= text_field_tag(:name, nil, class:"fancy-input") %>
      </p>

      <p><%= submit_tag('SUBMIT', class: "fancy-button") %></p>
    <% end %>
  </div>
  <div id="frank-robot">
    <%= image_tag("frank", :id => "manager")%>
  </div>
</div>