config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users

  resources :users do
    resources :robots, only: [:edit, :update]
  end

  resources :equities do
    resources :contracts, only: [:create, :new]
  end

  namespace :api do
    resources :graphs, only: [:create] do
      collection do
        get 'graph_data'
      end
    end
  end

#Need to add more "excepts" to sessions

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  post "login" => "sessions#create"

  root 'sessions#new'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one :robot
	has_many :contracts #, :order => 'created_at DESC'

  before_save :assign_robot
  before_save :fund_bank

  validates_presence_of :email
  validates_uniqueness_of :email
  validates_presence_of :username
  validates_uniqueness_of :username

  accepts_nested_attributes_for :robot, allow_destroy: true

  def assign_robot
    if self.robot == nil
      self.robot_attributes = { name: "YOLO" }
    end
  end

  def fund_bank
    if self.bank == nil
      self.bank = 500.00
    end
  end

  def logged_in?
    !!current_user
  end

  def self.verify_user(params)
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      @user
    else
      nil
    end
  end

  def calculate_bank
    self.bank = self.bank += self.contracts.sum(:gain_loss)
    self.update_attributes(:bank => bank)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      respond_to do |format|
        format.html
        format.js
      redirect_to edit_user_robot_path(@user, @user.robot)
      # flash[:notice] = "You signed up successfully"

      end
    else
      flash[:notice] = "Form is invalid"
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @contracts = @user.contracts
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/views/users/_new_user.html.erb
<div class="session-container">

  <%= form_for (@user, remote: true) do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= f.label :username %><br/>
      <%= f.text_field :username %>
    </p>
    <p>
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </p>
    <p class="button"><%= f.submit %></p>
  <% end %>
</div>

app/views/users/_signup_form.html.erb
  <%= form_for(@user, remote: true, html: {class: 'login-form'}) do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p class="fancy-field">
      <%= f.label :username, 'USERNAME' %><br/>
      <%= f.text_field :username, class: "fancy-input" %>
    </p>
    <p class="fancy-field">
      <%= f.label :email, 'EMAIL' %><br />
      <%= f.text_field :email, class: "fancy-input" %>
    </p>
    <p class="fancy-field">
      <%= f.label :password, 'PASSWORD' %><br />
      <%= f.password_field :password, class: "fancy-input" %>
    </p>
    <p class="fancy-field">
      <%= f.label :password_confirmation, 'CONFIRM PASSWORD' %><br />
      <%= f.password_field :password_confirmation, class: "fancy-input" %>
    </p>

    <p><%= f.submit 'SUBMIT', class: "fancy-button" %></p>
  <% end %>

app/views/users/index.html.erb
<h1>Welcome to the user index</h1>

<% @users.each do |user| %>
<p>
	<%= link_to user.username, user_path(user) %><br>
</p>
<% end %>

<div>
	<%= form_tag graph_data_api_graphs_path, remote: true do %>
		<%= hidden_field_tag(:ticker, 'AAPL') %>

		<div class="col-sm-2">
      <%= submit_tag 'AAPL' %>
    </div>
  <% end %>
</div>

<div>
	<%= form_tag graph_data_api_graphs_path, remote: true do %>
		<%= hidden_field_tag(:ticker, 'AA') %>

		<div class="col-sm-2">
      <%= submit_tag 'AA' %>
    </div>
  <% end %>
</div>

<%= render 'graphs/graph' %>

app/views/users/new.html.erb
<div class="session-container">
  <%= render 'users/signup_form' %>
</div>

app/views/users/new.js.erb
$("#user-form-container").slideDown('slow');
$(".login-form").css("margin-bottom", 240);
$("#user-form-container").html("<%= j (render :partial => 'signup_form') %>");

app/views/users/show.html.erb
<h1>User Profile</h1>

<p>
  <strong>email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<%= table_for @contracts do -%>
  <% columns :ticker, :strike_price, :spot_price, :sold_price, :interval, :gain_loss, :expiration_date, :put_call %>
<% end %>