config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users

  resources :users do
    resources :robots, only: [:edit, :update]
  end

  resources :equities do
    resources :contracts, only: [:create, :new]
  end

  namespace :api do
    resources :graphs, only: [:create] do
      collection do
        get 'graph_data'
      end
    end
  end

#Need to add more "excepts" to sessions

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  post "login" => "sessions#create"

  root 'sessions#new'
end

app/models/equity.rb
require 'alpha_adapter'

class Equity < ApplicationRecord

  has_many :contracts

  def self.last_refreshed(ticker)
    AlphaAdapter.search(ticker)["Meta Data"]["3. Last Refreshed"]
  end

  def self.get_price(ticker, time = last_refreshed(ticker))
    response = AlphaAdapter.search(ticker)
    price = response["Time Series (1min)"][time]["4. close"]
  end

  def self.get_roc(ticker)
    response = AlphaAdapter.roc(ticker)
    last_response_time = response["Meta Data"]["3: Last Refreshed"]
    response["Technical Analysis: ROC"][last_response_time]["ROC"]
  end

  def self.get_rsi(ticker)
    response = AlphaAdapter.rsi(ticker)
    last_response_time = response["Meta Data"]["3: Last Refreshed"]
    time_without_seconds = last_response_time.chomp[0..-4]
    response["Technical Analysis: RSI"][time_without_seconds]["RSI"]
  end

  def self.get_mfi(ticker)
    response = AlphaAdapter.mfi(ticker)
    last_response_time = response["Meta Data"]["3: Last Refreshed"]
    response["Technical Analysis: MFI"][last_response_time]["MFI"]
  end

  def self.get_adx(ticker)
    response = AlphaAdapter.adx(ticker)
    last_response_time = response["Meta Data"]["3: Last Refreshed"]
    time_without_seconds = last_response_time.chomp[0..-4]
    response["Technical Analysis: ADX"][time_without_seconds]["ADX"]
  end

  def self.get_obv(ticker)
    response = AlphaAdapter.obv(ticker)
    last_response_time = response["Meta Data"]["3: Last Refreshed"]
    response["Technical Analysis: OBV"][last_response_time]["OBV"]
  end

  def self.get_sma(ticker)
    response = AlphaAdapter.sma(ticker)
    last_response_time = response["Meta Data"]["3: Last Refreshed"]    
    response["Technical Analysis: SMA"][last_response_time]["SMA"]
  end

  def self.get_ema(ticker)
    response = AlphaAdapter.ema(ticker)
    last_response_time = response["Meta Data"]["3: Last Refreshed"]
    response["Technical Analysis: EMA"][last_response_time]["EMA"]
  end

  def self.get_stoch_d(ticker)
    response = AlphaAdapter.stoch(ticker)
    last_response_time = response["Meta Data"]["3: Last Refreshed"]
    time_without_seconds = last_response_time.chomp[0..-4]
    response["Technical Analysis: STOCH"][time_without_seconds]["SlowD"]
  end

  def self.get_stoch_k(ticker)
    response = AlphaAdapter.stoch(ticker)
    last_response_time = response["Meta Data"]["3: Last Refreshed"]
    time_without_seconds = last_response_time.chomp[0..-4]
    response["Technical Analysis: STOCH"][time_without_seconds]["SlowK"]
  end

end

app/controllers/equities_controller.rb
class EquitiesController < ApplicationController
  include ContractsHelper
  include BankHelper

  def index
	@user = User.find(session[:user_id])
  end

  def show
	  if logged_in?
      @user = current_user
      @equity = Equity.find_by_id(params[:id])
      @contracts = current_user.contracts.order("created_at DESC").select{|contract| contract.ticker == @equity.ticker }
	    @contract = Contract.new
	    @bankroll = bankroll
    else
      redirect_to new_user_path
    end
  end

end

app/views/equities/_fundamentals.html.erb
<div class='fundamental'>
  <div class='fundamental-column'>
    ROC: <%= @equity.roc %><br>
    RSL: <%= @equity.rsl %><br>
    MFL: <%= @equity.mfl %><br>
    ADX: <%= @equity.adx %><br>
    OBV: <%= @equity.obv %><br>
  </div>
  <div class='fundamental-column'>
    SMA: <%= @equity.sma %><br>
    EMA: <%= @equity.ema %><br>
    Stoch_D: <%= @equity.stoch_d %><br>
    Stoch_K: <%= @equity.stoch_k %><br>
  </div>
</div>

app/views/equities/_history.html.erb
<% if @contracts %>
  <%= table_for contracts do -%>
      <% column :ticker, :width => "10%" %>
      <% column :put_call, :width => "10%" %>
      <% column :strike_price, :width => "10%" %>
      <% column :interval, :width => "10%" %>
      <% column :expiration, :width => "10%" %>
      <% column :gain_loss, :width => "10%" %>
  <% end %>
<% else %>
  <p>No contracts yet.</p>
<% end %>


<!-- .in_time_zone("Pacific Time (US & Canada)").to_s.split(" ").second -->

app/views/equities/_indicators.html.erb
<% if @equity %>
<div class='fundamental'>
  <div class='fundamental-column'>
    Rate of Change(ROC): <%= @equity.roc %><br>
    Relative Strength Index(RSI): <%= @equity.rsi %><br>
    Money Flow Index(MFI): <%= @equity.mfi %><br>
    Average Directional Movement Index(ADX): <%= @equity.adx %><br>
    On Balance Volume(OBV): <%= @equity.obv %><br>
  </div>
  <div class='fundamental-column'>
    Simple Moving Average(SMA): <%= @equity.sma %><br>
    Exponential Moving Average(EMA): <%= @equity.ema %><br>
    Stochastic_D: <%= @equity.stoch_d %><br>
    Stochastic_K: <%= @equity.stoch_k %><br>
  </div>
</div>
<% else %>
  <p>You have to choose a stock... fundamentally.</p>
<% end  %>

app/views/equities/_overview.html.erb
<% if @equity %>
Ticker: <%= @equity.ticker %><br>
Name: <%= @equity.company_name %><br>
Description: <%= @equity.description %><br>
<% else %>
<p> Choose a ticker up there! </p>
<% end %>

app/views/equities/_trade.html.erb
<% if @equity %>
  <% if !markets_open? %>
    <p>Markets are currently closed. Any contract created will default to a $0 gain/loss.</p>
  <% end %>
  
  <%= form_for [equity, contract], url: equity_contracts_path(equity, contract) do |f| %>
    <p>
      <%= f.label :ticker, "Ticker:  " %>
      <%= equity.ticker %>
      <%= f.hidden_field :ticker, value: equity.ticker %>
    </p>
    <p>
      <%= f.label :put_call, "Type:  " %>
      <%= f.select :put_call, ['Call', 'Put'] %>
    </p>
    <p>
      <%= f.label :interval, "Option Interval in Minutes:  " %>
      <%= f.select :interval, ['1', '5', '15', '60'] %>
    </p>
    <p>
      <%= f.label :strike_price, "Strike Price:  " %>
      <%= f.number_field :strike_price, class: :text_field, step: :any %>
    </p>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :equity_id, value: equity.id %>
    <p>
      <%= f.submit %>
    </p>
  <% end %>
<% else %>
  <p>Choose a ticker first!</p>
<% end %>

app/views/equities/index.html.erb
<div id="equities-container">
  <div class='stockbox'>
    <div class='button'><%= link_to "TSLA", equity_path(1), class: 'stock-link' %></div>
    <div class='button'><%= link_to "GOOGL", equity_path(2), class: 'stock-link'  %></div>
    <div class='button'><%= link_to "AAPL", equity_path(3), class: 'stock-link' %></div>
    <div class='button'><%= link_to "FB", equity_path(4), class: 'stock-link' %></div>
    <div class='button'><%= link_to "TWTR", equity_path(5), class: 'stock-link' %></div>
  </div>

  <h3>Hey <%= @user.username.capitalize %>! </h3>
  <p id="instructions" >It's me, <%= @user.robot.name.capitalize %>.
    <br>I'm your mentor robot here at PCP.
    <br>On your left are the stocks
    <br>that you can play with.
    <br>Go ahead and click one of them.
  </p>

  <div id="mentor-robot">
    <img src="<%= @user.robot.summon %>" alt="Robot Mentor">
  </div>

  <div id='bankroll'>
    <div id=bank-label>BANK</div>
    <br><%= sprintf "%.2f", @user.bank %></div>
  </div>


  <div class=infobox>
    <br>
    <br>
     <ul class="tabs">
        <li><a href='#overview'>Overview</a></li>
        <li><a href='#fundamentals'>Fundamentals</a></li>
        <li><a href='#trade'>Trade</a></li>
        <li><a href='#history'>History</a></li>
    </ul>
    <div class='items'>
      <div id="overview" class='tab'>
        <%= render partial: "overview", locals: {@equity => @equity} %>
      </div>
      <div id="fundamentals" class='tab'>
        <%= render partial: "indicators" %>
      </div>
      <div id="trade" class='tab'>
        <%= render partial: "trade", locals: {equity: @equity, contract: @contract} %>
      </div>
      <div id="history" class='tab'>
        <%= render partial: "history", locals: {equity: @equity, contract: @contract} %>
      </div>
    </div>
  </div>
  <div id="graph"><%= render 'graphs/graph' %></div>
</div>

app/views/equities/show.html.erb
<div id="equities-container">
  <div id="graph"><%= render 'graphs/graph' %></div>

  <div class='stockbox'>
    <div class='button'><%= link_to "TSLA", equity_path(1), class: 'stock-link' %></div>
    <div class='button'><%= link_to "GOOGL", equity_path(2), class: 'stock-link'  %></div>
    <div class='button'><%= link_to "AAPL", equity_path(3), class: 'stock-link' %></div>
    <div class='button'><%= link_to "FB", equity_path(4), class: 'stock-link' %></div>
    <div class='button'><%= link_to "TWTR", equity_path(5), class: 'stock-link' %></div>
  </div>

  <h3 id="ohhey">Hey <%= @user.username.capitalize %>! </h3>
  <p id="instructions" >It's me, <%= @user.robot.name.capitalize %>.
    <br>I'm your mentor robot here at PCP.
    <br>On your left are the stocks
    <br>that you can play with.
    <br>Go ahead and click one of them.
  </p>

  <div id="mentor-robot">
    <img src="<%= @user.robot.summon %>" alt="Robot Mentor">
  </div>

  <div id='bankroll'>
    <div id=bank-label>BANK</div>
    <br>$<%= sprintf "%.2f", @user.bank %></div>
  </div>

  <div class=infobox>
    <br>
    <br>
     <ul class="tabs">
        <li><a href='#overview'>Overview</a></li>
        <li><a href='#fundamentals'>Fundamentals</a></li>
        <li><a href='#trade'>Trade</a></li>
        <li><a href='#history'>History</a></li>
    </ul>
    <div class='items'>
      <div id="overview" class='tab'>
        <%= render partial: "overview", locals: {@equity => @equity} %>
      </div>
      <div id="fundamentals" class='tab'>
        <%= render partial: "indicators" %>
      </div>
      <div id="trade" class='tab'>
        <%= render partial: "trade", locals: {equity: @equity, contract: @contract} %>
      </div>
      <div id="history" class='tab'>
        <%= render partial: "history", locals: {equity: @equity, contract: @contract, contracts: @contracts} %>
      </div>
    </div>
  </div>

</div>